include         /etc/ldap/schema/core.schema
include         /etc/ldap/schema/cosine.schema
include         /etc/ldap/schema/inetorgperson.schema

pidfile         /var/run/slapd/slapd.pid
argsfile        /var/run/slapd/slapd.args

loglevel        256

database        mdb
suffix          "dc=ladvik,dc=local"
rootdn          "cn=admin,dc=ladvik,dc=local"
rootpw          admin123
directory       /var/lib/ldap
maxsize         1073741824

index           objectClass eq
index           uid eq
index           mail eq
index           cn eq
