-- =============================================================================
-- 02_data.sql — Guacamole connections and RBAC
--
-- RUNS AFTER: 01_schema.sql (the Guacamole table definitions from setup.sh)
-- RUNS BY: PostgreSQL's docker-entrypoint-initdb.d/ mechanism (first boot only)
--
-- THREE THINGS THIS FILE DOES:
--   1. Creates Guacamole user groups whose names MATCH the LDAP group CNs
--   2. Creates connection records for all 3 target machines
--   3. Grants READ permission on connections to the appropriate groups
--
-- THE CRITICAL MAPPING MECHANISM:
--   When Bob logs in, Guacamole:
--     a) Authenticates Bob via LDAP → discovers Bob is in 'cn=ssh-users'
--     b) Looks in the DB for a user_group named 'ssh-users' (string match)
--     c) Bob inherits all permissions of that DB user group
--   So: LDAP group CN must EXACTLY equal Guacamole user group name.
--
-- IMPORTANT: Users (bob, alice) are NOT created here.
--   They exist ONLY in LDAP. The DB only knows about groups and connections.
-- =============================================================================


-- =============================================================================
-- SECTION 1: USER GROUPS
--
-- guacamole_entity is the unified identity table.
-- It holds both USER and USER_GROUP records.
-- A user group entry requires TWO inserts:
--   1. One row in guacamole_entity (name + type)
--   2. One row in guacamole_user_group (references the entity, has disabled flag)
-- =============================================================================

-- ---- Group: ssh-users ----
-- This name MUST match the LDAP group's cn attribute exactly: 'ssh-users'
-- type = 'USER_GROUP' distinguishes this from a regular user entry
INSERT INTO guacamole_entity (name, type)
VALUES ('ssh-users', 'USER_GROUP');

-- Link the group metadata row to the entity we just created
-- entity_id is auto-generated by the sequence — we SELECT it back by name
-- disabled = FALSE means the group is active (not suspended)
INSERT INTO guacamole_user_group (entity_id, disabled)
SELECT entity_id, FALSE
FROM guacamole_entity
WHERE name = 'ssh-users' AND type = 'USER_GROUP';


-- ---- Group: desktop-users ----
INSERT INTO guacamole_entity (name, type)
VALUES ('desktop-users', 'USER_GROUP');

INSERT INTO guacamole_user_group (entity_id, disabled)
SELECT entity_id, FALSE
FROM guacamole_entity
WHERE name = 'desktop-users' AND type = 'USER_GROUP';


-- =============================================================================
-- SECTION 2: CONNECTIONS
--
-- guacamole_connection stores the connection record (name + protocol).
-- guacamole_connection_parameter stores KEY=VALUE pairs for the connection.
-- ALL sensitive data (NPA password) lives here — users never see it.
--
-- NPA Account:
--   username: npa
--   password: npa_secure_password
--   This account exists on all 3 target machines (created in Dockerfiles).
--   Guacamole uses it to authenticate TO the target, not as the end-user identity.
-- =============================================================================

-- =============================================================================
-- Connection 1: Linux Server 1 (SSH)
-- Protocol: 'ssh' — tells guacd to use its SSH client
-- =============================================================================

-- Insert the connection itself
-- connection_name: what users see in the portal
-- parent_id: NULL means no folder grouping (root level)
-- protocol: 'ssh', 'rdp', or 'vnc' — determines which guacd plugin to use
INSERT INTO guacamole_connection (connection_name, protocol)
VALUES ('Linux Server 1 (SSH)', 'ssh');

-- hostname: the target machine's hostname/IP
-- Inside guac-net, Docker DNS resolves 'linux-server-1' to the container's IP
-- This is WHY all containers must be on the same Docker network
INSERT INTO guacamole_connection_parameter (connection_id, parameter_name, parameter_value)
SELECT connection_id, 'hostname', 'linux-server-1'
FROM guacamole_connection WHERE connection_name = 'Linux Server 1 (SSH)';

-- port: standard SSH port 22
-- guacd will connect to linux-server-1:22
INSERT INTO guacamole_connection_parameter (connection_id, parameter_name, parameter_value)
SELECT connection_id, 'port', '22'
FROM guacamole_connection WHERE connection_name = 'Linux Server 1 (SSH)';

-- username: the NPA account on the target machine
-- This is the Linux user that the SSH connection will authenticate as
INSERT INTO guacamole_connection_parameter (connection_id, parameter_name, parameter_value)
SELECT connection_id, 'username', 'npa'
FROM guacamole_connection WHERE connection_name = 'Linux Server 1 (SSH)';

-- password: the NPA account's password
-- Stored in the DB — Guacamole sends this to guacd, which sends it to sshd
-- End users never see or know this password
INSERT INTO guacamole_connection_parameter (connection_id, parameter_name, parameter_value)
SELECT connection_id, 'password', 'npa_secure_password'
FROM guacamole_connection WHERE connection_name = 'Linux Server 1 (SSH)';


-- =============================================================================
-- Connection 2: Linux Server 2 (SSH)
-- Identical setup to Server 1, different hostname
-- =============================================================================

INSERT INTO guacamole_connection (connection_name, protocol)
VALUES ('Linux Server 2 (SSH)', 'ssh');

INSERT INTO guacamole_connection_parameter (connection_id, parameter_name, parameter_value)
SELECT connection_id, 'hostname', 'linux-server-2'
FROM guacamole_connection WHERE connection_name = 'Linux Server 2 (SSH)';

INSERT INTO guacamole_connection_parameter (connection_id, parameter_name, parameter_value)
SELECT connection_id, 'port', '22'
FROM guacamole_connection WHERE connection_name = 'Linux Server 2 (SSH)';

INSERT INTO guacamole_connection_parameter (connection_id, parameter_name, parameter_value)
SELECT connection_id, 'username', 'npa'
FROM guacamole_connection WHERE connection_name = 'Linux Server 2 (SSH)';

INSERT INTO guacamole_connection_parameter (connection_id, parameter_name, parameter_value)
SELECT connection_id, 'password', 'npa_secure_password'
FROM guacamole_connection WHERE connection_name = 'Linux Server 2 (SSH)';


-- =============================================================================
-- Connection 3: Linux Desktop (RDP)
-- Protocol: 'rdp' — guacd uses its RDP client to connect to XRDP
-- RDP has more parameters than SSH because of display/encryption settings
-- =============================================================================

INSERT INTO guacamole_connection (connection_name, protocol)
VALUES ('Linux Desktop (RDP)', 'rdp');

INSERT INTO guacamole_connection_parameter (connection_id, parameter_name, parameter_value)
SELECT connection_id, 'hostname', 'linux-desktop'
FROM guacamole_connection WHERE connection_name = 'Linux Desktop (RDP)';

-- RDP standard port (Microsoft's standard, same as Windows RDP)
INSERT INTO guacamole_connection_parameter (connection_id, parameter_name, parameter_value)
SELECT connection_id, 'port', '3389'
FROM guacamole_connection WHERE connection_name = 'Linux Desktop (RDP)';

INSERT INTO guacamole_connection_parameter (connection_id, parameter_name, parameter_value)
SELECT connection_id, 'username', 'npa'
FROM guacamole_connection WHERE connection_name = 'Linux Desktop (RDP)';

INSERT INTO guacamole_connection_parameter (connection_id, parameter_name, parameter_value)
SELECT connection_id, 'password', 'npa_secure_password'
FROM guacamole_connection WHERE connection_name = 'Linux Desktop (RDP)';

-- security: 'any' lets XRDP and guacd negotiate the best security layer
-- Options: 'any', 'rdp' (classic), 'tls' (TLS), 'nla' (Network Level Auth)
-- For a playground with XRDP, 'any' is the most compatible setting
INSERT INTO guacamole_connection_parameter (connection_id, parameter_name, parameter_value)
SELECT connection_id, 'security', 'any'
FROM guacamole_connection WHERE connection_name = 'Linux Desktop (RDP)';

-- ignore-cert: XRDP generates a self-signed TLS certificate on first run
-- Setting this to 'true' tells guacd not to reject self-signed certs
-- In production, use a proper CA-signed cert and set this to 'false'
INSERT INTO guacamole_connection_parameter (connection_id, parameter_name, parameter_value)
SELECT connection_id, 'ignore-cert', 'true'
FROM guacamole_connection WHERE connection_name = 'Linux Desktop (RDP)';

-- color-depth: 16-bit colour balances visual quality and bandwidth
-- Options: 8, 16, 24, 32 (bits per pixel)
INSERT INTO guacamole_connection_parameter (connection_id, parameter_name, parameter_value)
SELECT connection_id, 'color-depth', '16'
FROM guacamole_connection WHERE connection_name = 'Linux Desktop (RDP)';

-- resize-method: 'display-update' tells the server to resize when the
-- browser window changes size (better user experience)
INSERT INTO guacamole_connection_parameter (connection_id, parameter_name, parameter_value)
SELECT connection_id, 'resize-method', 'display-update'
FROM guacamole_connection WHERE connection_name = 'Linux Desktop (RDP)';


-- =============================================================================
-- SECTION 3: RBAC PERMISSIONS
--
-- guacamole_connection_permission maps an ENTITY (user or group) to a CONNECTION
-- with a permission type. We use 'READ' which means "can see and use this connection".
-- Other types: 'UPDATE' (can edit), 'DELETE' (can remove), 'ADMINISTER' (can grant)
--
-- We grant permissions TO GROUPS (not to individual users).
-- This is the "group-based RBAC, do not bind users to access roles" requirement.
--
-- HOW CROSS JOIN WORKS HERE:
--   We want: for every entity_id where name='ssh-users' AND
--            for every connection_id where connection_name IN (...)
--   CROSS JOIN pairs each entity row with each connection row.
--   The WHERE clause filters to exactly the rows we want.
--   Result: 1 entity × 2 connections = 2 permission rows inserted.
-- =============================================================================

-- Grant ssh-users group READ access to both SSH connections
-- Bob is in ssh-users → Bob can see and open Linux Server 1 and Server 2
-- Alice is in desktop-users → Alice does NOT see these (no permission row)
INSERT INTO guacamole_connection_permission (entity_id, connection_id, permission)
SELECT
  e.entity_id,
  c.connection_id,
  'READ'::guacamole_object_permission_type   -- cast string to the enum type
FROM
  guacamole_entity e                          -- source: entity table (our groups)
  CROSS JOIN guacamole_connection c           -- pair with connection table
WHERE
  e.name = 'ssh-users'                        -- only the ssh-users group entity
  AND e.type = 'USER_GROUP'                   -- make sure it's a group, not a user
  AND c.connection_name IN (                  -- only SSH connections
    'Linux Server 1 (SSH)',
    'Linux Server 2 (SSH)'
  );


-- Grant desktop-users group READ access to the RDP connection
-- Alice is in desktop-users → Alice can see and open Linux Desktop
-- Bob is in ssh-users → Bob does NOT see the desktop (no permission row)
INSERT INTO guacamole_connection_permission (entity_id, connection_id, permission)
SELECT
  e.entity_id,
  c.connection_id,
  'READ'::guacamole_object_permission_type
FROM
  guacamole_entity e
  CROSS JOIN guacamole_connection c
WHERE
  e.name = 'desktop-users'
  AND e.type = 'USER_GROUP'
  AND c.connection_name = 'Linux Desktop (RDP)';
